//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63131920.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Admin
    {
        public int id { get; set; }
        [DisplayName("Họ tên")]
        public string fullname { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Mật khẩu")]
        public string password { get; set; }
    }
}
