//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63131920.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLCH_63131920Entities : DbContext
    {
        public QLCH_63131920Entities()
            : base("name=QLCH_63131920Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order_details> Order_details { get; set; }
        public virtual DbSet<Product_item> Product_item { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shipping_method> Shipping_method { get; set; }
        public virtual DbSet<Shop_order> Shop_order { get; set; }
        public virtual DbSet<Shopping_cart> Shopping_cart { get; set; }
        public virtual DbSet<Shopping_cart_item> Shopping_cart_item { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Variation> Variations { get; set; }
        public virtual DbSet<Variation_option> Variation_option { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
    }
}
