//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63131920.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Product_item = new HashSet<Product_item>();
        }
    
        public int id { get; set; }
        [DisplayName("Tên sản phẩm")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public string product_name { get; set; }
        public int category_id { get; set; }
        [DisplayName("Giá")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int price { get; set; }
        [DisplayName("Mô tả")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        [AllowHtml]
        public string description { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Vui lòng không để trống")]
        public int qty_in_stock { get; set; }
        [DisplayName("Ảnh sản phẩm")]
        public string product_image { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_item> Product_item { get; set; }
    }
}
