//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63131920.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_cart_item
    {
        public int id { get; set; }
        public int cart_id { get; set; }
        public int qty { get; set; }
        public int product_id { get; set; }
    
        public virtual Product_item Product_item { get; set; }
        public virtual Shopping_cart Shopping_cart { get; set; }
    }
}
