//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63131920.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop_order()
        {
            this.Order_details = new HashSet<Order_details>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public System.DateTime order_date { get; set; }
        public int shipping_address { get; set; }
        public int shipping_method { get; set; }
        public int order_total { get; set; }
        public bool order_status { get; set; }
        public string payment_method { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_details> Order_details { get; set; }
        public virtual Shipping_method Shipping_method1 { get; set; }
        public virtual User User { get; set; }
    }
}
