//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63131920.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Shop_order = new HashSet<Shop_order>();
            this.Shopping_cart = new HashSet<Shopping_cart>();
            this.Addresses = new HashSet<Address>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Vui lòng không để trống")]
        [DisplayName("Họ tên")]
        public string fullname { get; set; }
        [Required(ErrorMessage = "Vui lòng không để trống")]

        [DisplayName("Email")]
        [RegularExpression(@"^\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b", ErrorMessage = "Định dạng email không đúng")]
        public string email { get; set; }
        [Required(ErrorMessage = "Vui lòng không để trống")]
        [DisplayName("Số điện thoại")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Số điện thoại phải có 10 chữ số")]
        public string phone_number { get; set; }

        [Required(ErrorMessage = "Vui lòng không để trống")]
        [DisplayName("Mật khẩu")]
        public string password { get; set; }
        [DisplayName("Giới tính")]
        public bool sex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop_order> Shop_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shopping_cart> Shopping_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
